#!/bin/sh
# calls program ga_gisop and masks regions
#call cmd="ga_td_svmop_multi @class@ @VEC_TYPE@ @LIST_OB_CLASSES@ @LIST_SUB_CLASSES@ @shape_dir@ @context_region@ @context_type@ @mask_file@ @geoWest@ @geoNorth@ @geoEast@ @geoSouth@ @label_res@ @output@">

SUCCESS=0
FAILURE=1

if [ $# -eq 14 ]; then
    echo "svm_class \"$1\" \"$2\" \"$3\" \"$4\" \"0\" SHAPE \"$5\" \"$6\" \"$7\" \"$9\" \"${10}\" \"${11}\" \"${12}\" \"${13}\" \"${14}\""
    svm_class "$1" "$2" "$3" "$4" "0" SHAPE "$5" "$6" "$7" "$9" "${10}" "${11}" "${12}" "${13}" "${14}" || exit $?
    
    #mask result of ga_svmop
    if [ -n "$8" ] 
        then
        echo "regionmask ${14} $8"
        regionmask ${14} $8 || exit $?
    fi

    exit $SUCCESS
else
    # print usage information
    echo " "
    echo "ga_td_svmop_multi"
    echo "                  number of input channels"
    echo "                  input channel 1"
    echo "                  ..."
    echo "                  input channel n"
    echo "                  svm configuration"
    echo "                  svm scaling configuration"
    echo "                  output file"
    echo " "

    exit $FAILURE
fi
